import { Teacher } from "@/types/teacher";

export const teachers: Teacher[] = [
  {
    id: "1",
    name: "Anjali Verma",
    subject: "Mathematics",
    email: "anjali.verma@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    joinedOn: "2023-01-15",
    phone: "9876543210",
    from: "Delhi",
    experience: 5,
    schedule: {
      Monday: "Algebra 9am",
      Tuesday: "Trigonometry 10am",
      Wednesday: "Geometry 11am",
      Thursday: "Probability 9am",
      Friday: "Calculus 10am",
      Saturday: "Doubt Clearing 11am",
    },
    qualifications: [
      { name: "Algebra Basics", rate: 25, type: "private" },
      { name: "Trigonometry Advanced", rate: 30, type: "private" },
      { name: "Math Group Class", rate: 20, type: "group" }
    ]
  },
  {
    id: "2",
    name: "Rohit Sharma",
    subject: "Physics",
    email: "rohit.sharma@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    joinedOn: "2022-08-10",
    phone: "8765432109",
    from: "Mumbai",
    experience: 7,
    schedule: {
      Monday: "Mechanics 10am",
      Tuesday: "Thermodynamics 11am",
      Wednesday: "Optics 9am",
      Thursday: "Electrostatics 12pm",
      Friday: "Magnetism 10am",
      Saturday: "Revision 9am",
    },
    qualifications: [
      { name: "Mechanics Core", rate: 28, type: "private" },
      { name: "Physics Lab Group", rate: 22, type: "group" }
    ]
  },
  {
    id: "3",
    name: "Neha Patil",
    subject: "Chemistry",
    email: "neha.patil@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    joinedOn: "2021-05-25",
    phone: "9123456789",
    from: "Pune",
    experience: 4,
    schedule: {
      Monday: "Organic 10am",
      Tuesday: "Inorganic 9am",
      Wednesday: "Physical 11am",
      Thursday: "Lab Work 2pm",
      Friday: "Equations 10am",
      Saturday: "Mock Test 12pm",
    },
    qualifications: []
  },
  {
    id: "4",
    name: "Aman Khan",
    subject: "English",
    email: "aman.khan@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    joinedOn: "2020-11-01",
    phone: "9988776655",
    from: "Lucknow",
    experience: 6,
    schedule: {
      Monday: "Grammar 9am",
      Tuesday: "Literature 10am",
      Wednesday: "Essay Writing 11am",
      Thursday: "Reading Skills 9am",
      Friday: "Speaking Practice 10am",
      Saturday: "Debate 11am",
    },
    qualifications: []
  },
  {
    id: "5",
    name: "Sneha Kapoor",
    subject: "Biology",
    email: "sneha.kapoor@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/5.jpg",
    joinedOn: "2023-04-12",
    phone: "9001122334",
    from: "Bangalore",
    experience: 3,
    schedule: {
      Monday: "Botany 8am",
      Tuesday: "Zoology 9am",
      Wednesday: "Genetics 10am",
      Thursday: "Human Anatomy 11am",
      Friday: "Lab 1pm",
      Saturday: "Quiz 9am",
    },
    qualifications: []
  },
  {
    id: "6",
    name: "Kunal Joshi",
    subject: "History",
    email: "kunal.joshi@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    joinedOn: "2019-03-20",
    phone: "8456781230",
    from: "Chandigarh",
    experience: 8,
    schedule: {
      Monday: "Ancient India 9am",
      Tuesday: "Medieval India 10am",
      Wednesday: "Modern India 11am",
      Thursday: "World History 10am",
      Friday: "Freedom Movement 9am",
      Saturday: "Test 12pm",
    },
    qualifications: []
  },
  {
    id: "7",
    name: "Priya Singh",
    subject: "Geography",
    email: "priya.singh@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/7.jpg",
    joinedOn: "2021-07-14",
    phone: "9765432100",
    from: "Jaipur",
    experience: 6,
    schedule: {
      Monday: "Earth 10am",
      Tuesday: "Rivers 11am",
      Wednesday: "Mountains 9am",
      Thursday: "Maps 10am",
      Friday: "Resources 11am",
      Saturday: "Assignment 12pm",
    },
    qualifications: []
  },
  {
    id: "8",
    name: "Sanjay Mehta",
    subject: "Computer Science",
    email: "sanjay.mehta@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    joinedOn: "2020-09-01",
    phone: "9090909090",
    from: "Hyderabad",
    experience: 5,
    schedule: {
      Monday: "C++ 9am",
      Tuesday: "Java 10am",
      Wednesday: "Python 11am",
      Thursday: "DSA 10am",
      Friday: "SQL 9am",
      Saturday: "Debugging 12pm",
    },
    qualifications: []
  },
  {
    id: "9",
    name: "Megha Jain",
    subject: "Economics",
    email: "megha.jain@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/9.jpg",
    joinedOn: "2022-01-19",
    phone: "9212345678",
    from: "Indore",
    experience: 4,
    schedule: {
      Monday: "Microeconomics 9am",
      Tuesday: "Macroeconomics 10am",
      Wednesday: "Trade 11am",
      Thursday: "Budget 10am",
      Friday: "GDP 9am",
      Saturday: "Discussion 12pm",
    },
    qualifications: []
  },
  {
    id: "10",
    name: "Aditya Rao",
    subject: "Political Science",
    email: "aditya.rao@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/10.jpg",
    joinedOn: "2018-05-10",
    phone: "7890123456",
    from: "Kolkata",
    experience: 9,
    schedule: {
      Monday: "Indian Constitution 10am",
      Tuesday: "Democracy 9am",
      Wednesday: "Governance 11am",
      Thursday: "Laws 10am",
      Friday: "Judiciary 11am",
      Saturday: "Q&A 12pm",
    },
    qualifications: []
  },
  {
    id: "11",
    name: "Riya Chatterjee",
    subject: "Psychology",
    email: "riya.chat@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/11.jpg",
    joinedOn: "2023-02-10",
    phone: "9856123784",
    from: "Kolkata",
    experience: 3,
    schedule: {
      Monday: "Intro to Psych 10am",
      Tuesday: "Behavioral 11am",
      Wednesday: "Cognitive 9am",
      Thursday: "Developmental 10am",
      Friday: "Practical 11am",
      Saturday: "Case Study 12pm",
    },
    qualifications: []
  },
  {
    id: "12",
    name: "Deepak Kulkarni",
    subject: "Sanskrit",
    email: "deepak.kul@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/12.jpg",
    joinedOn: "2021-08-01",
    phone: "9008899000",
    from: "Nashik",
    experience: 6,
    schedule: {
      Monday: "Shlokas 9am",
      Tuesday: "Grammar 10am",
      Wednesday: "Literature 11am",
      Thursday: "Writing 10am",
      Friday: "Translation 9am",
      Saturday: "Quiz 11am",
    },
    qualifications: []
  },
  {
    id: "13",
    name: "Kavita Desai",
    subject: "Hindi",
    email: "kavita.desai@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/13.jpg",
    joinedOn: "2022-10-05",
    phone: "7894561230",
    from: "Ahmedabad",
    experience: 4,
    schedule: {
      Monday: "Vyakaran 9am",
      Tuesday: "Kavita 10am",
      Wednesday: "Nibandh 11am",
      Thursday: "Path 10am",
      Friday: "Listening 11am",
      Saturday: "Practice 12pm",
    },
    qualifications: []
  },
  {
    id: "14",
    name: "Harsh Vardhan",
    subject: "EVS",
    email: "harsh.v@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/14.jpg",
    joinedOn: "2023-06-15",
    phone: "8812345678",
    from: "Raipur",
    experience: 2,
    schedule: {
      Monday: "Water 8am",
      Tuesday: "Plants 9am",
      Wednesday: "Soil 10am",
      Thursday: "Recycling 11am",
      Friday: "Climate 9am",
      Saturday: "Quiz 10am",
    },
    qualifications: []
  },
  {
    id: "15",
    name: "Pooja Iyer",
    subject: "Art & Craft",
    email: "pooja.iyer@example.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/15.jpg",
    joinedOn: "2023-07-01",
    phone: "8899776655",
    from: "Chennai",
    experience: 3,
    schedule: {
      Monday: "Sketching 9am",
      Tuesday: "Painting 10am",
      Wednesday: "Origami 11am",
      Thursday: "Clay 10am",
      Friday: "Color Mixing 9am",
      Saturday: "Exhibition Prep 12pm",
    },
    qualifications: []
  }
];
